services:
  - type: web
    name: careercraft-backend
    runtime: python
    buildCommand: pip install -r requirements.txt && python -m nltk.downloader stopwords
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: GOOGLE_API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
